[build]
  publish = "dist"
  command = "CI= npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SENTRY_ENV = "production"
  VITE_API_BASE_URL = "https://carbonai-backend.onrender.com"

[context.deploy-preview.environment]
  VITE_SENTRY_ENV = "staging"
  VITE_API_BASE_URL = "https://carbonai-backend.onrender.com"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"