services:
  - type: web
    name: carbonledgerai-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_cCQidTB07kpV@ep-wild-salad-ab87glrm-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: JWT_SECRET
        value: EDIJDIOMDSDSKSKsddkssdkld456789
      - key: CORS_ORIGIN
        value: https://glittering-sunshine-6d05d2.netlify.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100